### ISSUE TITLE
Shrink TVP for prediction?

### ISSUE THREAD

**Issue by dklinenberg2020** [cran/shrinkTVP#1]
Hi! I'm a big fan of the `ShrinkTVP` package. I'm working on a paper using non-centered parameterization to add to `CausalImpact`. I figured it would be cool to see if ShrinkTVP has similar predictive capabilities as CausalImpact...or better! I tried writing a wrapper so that the model can produce a counterfactual as is done in CausalImpact, but it has very very very large credibility intervals. Have the authors tried doing this as well and received similar results?

I've attached the wrapper function and test data to this post (comparing to CausalImpact with and without TVP). I'd love to hear if you found similar results! Thanks
[bitto_model.R.zip](https://github.com/cran/shrinkTVP/files/7975835/bitto_model.R.zip)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
